import { firebaseConfig } from './firebase-config.js';
import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import { getFirestore, doc, getDoc, setDoc, addDoc, collection, query, orderBy, onSnapshot, serverTimestamp, updateDoc, deleteDoc, getDocs, writeBatch } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';
const fb=initializeApp(firebaseConfig); const db=getFirestore(fb);
const stores=['板橋大遠百','樹林','中和','南港','汐止','天母','比漾','忠孝'];
const fines=[['防盜檢查缺失',50],['盤點當日未結案',50],['盤點未過帳',50],['立牌、海報未準時更換',50],['AI稽核申訴完未達100分',300],['內稽原始分數未達85分',300]];
const rewards=[['內稽原始分數達95分',1000],['區內總門號達成100%',3000]];
let state={user:null,tab:'home',records:[],fund:[],users:[],settings:{fundBalance:200}}; const $=s=>document.querySelector(s); const app=$('#app');
async function init(){ const s=await getDoc(doc(db,'meta','settings')); if(!s.exists()) await setDoc(doc(db,'meta','settings'),{fundBalance:200,createdAt:serverTimestamp()}); const admin=await getDoc(doc(db,'users','5052')); if(!admin.exists()) await setDoc(doc(db,'users','5052'),{employeeId:'5052',name:'佩佩',password:'5052',role:'admin',active:true,createdAt:serverTimestamp()}); renderLogin(); }
function renderLogin(){app.innerHTML=`<div class="login"><div class="login-card"><img class="logo" src="./logo.png"><h1>北二獎懲基金App</h1><div class="sub">一起努力・一起成長 🌱</div><div class="field"><label>員編</label><input id="emp" inputmode="numeric" placeholder="例如 5052"></div><div class="field"><label>密碼</label><input id="pwd" type="password" placeholder="預設與員編相同"></div><button id="loginBtn" style="width:100%">登入</button><p class="small muted">管理員預設：5052／佩佩，密碼 5052</p></div></div>`;$('#loginBtn').onclick=login;}
async function login(){const id=$('#emp').value.trim(),pwd=$('#pwd').value.trim(); const snap=await getDoc(doc(db,'users',id)); if(!snap.exists()) return alert('找不到此員編'); const u=snap.data(); if(!u.active) return alert('此帳號已停用'); if(u.password!==pwd) return alert('密碼錯誤'); state.user=u; subscribe();}
function subscribe(){onSnapshot(query(collection(db,'records'),orderBy('createdAt','desc')),s=>{state.records=s.docs.map(d=>({id:d.id,...d.data()}));render();});onSnapshot(query(collection(db,'fundLedger'),orderBy('createdAt','desc')),s=>{state.fund=s.docs.map(d=>({id:d.id,...d.data()}));render();});onSnapshot(collection(db,'users'),s=>{state.users=s.docs.map(d=>({id:d.id,...d.data()}));render();});onSnapshot(doc(db,'meta','settings'),s=>{if(s.exists())state.settings=s.data();render();});}
function totals(){let fine=state.records.filter(r=>r.type==='fine').reduce((a,b)=>a+(+b.amount||0),0);let reward=state.records.filter(r=>r.type==='reward').reduce((a,b)=>a+(+b.amount||0),0);let income=state.fund.filter(r=>r.kind==='income').reduce((a,b)=>a+(+b.amount||0),0);let expense=state.fund.filter(r=>r.kind==='expense').reduce((a,b)=>a+(+b.amount||0),0);return{fine,reward,income,expense,balance:(state.settings.fundBalance||0)+fine+reward+income-expense};}
function shell(content){const t=totals();app.innerHTML=`<div class="wrap"><div class="top"><div class="brand"><img src="./logo.png"><div><b>北二獎懲基金App</b><div class="small muted">${state.user?.name||''}・${state.user?.employeeId||''}</div></div></div><button class="secondary" onclick="location.reload()">登出</button></div>${content}</div><div class="nav">${[['home','🏠 首頁'],['fine','🏪 罰款'],['reward','⭐ 獎勵'],['fund','💰 基金'],['history','📜 紀錄'],['admin','⚙️ 管理']].map(x=>`<button class="${state.tab===x[0]?'active':''}" data-tab="${x[0]}">${x[1]}</button>`).join('')}</div>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render();});}
function render(){if(!state.user)return; const t=totals(); if(state.tab==='home') return shell(`<div class="grid"><div class="card"><div>本月罰款</div><div class="stat">$${t.fine}</div></div><div class="card"><div>本月獎勵</div><div class="stat">$${t.reward}</div></div><div class="card"><div>基金支出</div><div class="stat">$${t.expense}</div></div><div class="card"><div>預估區基金</div><div class="stat">$${t.balance}</div></div></div><div class="card"><h3>🌱 今日小提醒</h3><p>罰款紀錄分店，獎勵紀錄整區；手動月結後，本月獎懲歸零並加總到區基金。</p></div>`);
if(state.tab==='fine') return shell(`<div class="card"><h2>🏪 門市罰款</h2><div class="field"><label>選擇門市</label><select id="store">${stores.map(s=>`<option>${s}</option>`).join('')}</select></div><div class="actions">${fines.map(f=>`<button class="fine" data-fine="${f[0]}" data-amt="${f[1]}">${f[0]}<br>-$${f[1]}</button>`).join('')}</div></div>`),bindFine();
if(state.tab==='reward') return shell(`<div class="card"><h2>⭐ 整區獎勵</h2><div class="actions">${rewards.map(r=>`<button class="reward" data-reward="${r[0]}" data-amt="${r[1]}">${r[0]}<br>+$${r[1]}</button>`).join('')}</div></div>`),bindReward();
if(state.tab==='fund') return shell(`<div class="card"><h2>💰 區基金帳本</h2><div class="stat">目前預估 $${t.balance}</div><div class="grid"><div class="field"><label>類型</label><select id="kind"><option value="income">收入</option><option value="expense">支出</option></select></div><div class="field"><label>金額</label><input id="amt" inputmode="numeric"></div></div><div class="field"><label>備註</label><input id="note" placeholder="例如：購買聚餐用品"></div><button id="addFund">新增帳本紀錄</button></div><div class="list">${state.fund.map(r=>row(`${r.kind==='income'?'收入':'支出'} $${r.amount}`,r.note||'',r.id,'fundLedger')).join('')}</div>`),bindFund();
if(state.tab==='history') return shell(`<div class="card"><h2>📜 獎懲紀錄</h2><button id="exportImg" class="gold">匯出罰款結算圖 PNG</button> ${isAdmin()?'<button id="closeMonth" class="danger">本月結算並歸零</button>':''}</div><div id="receipt" class="receipt"><h2>北二獎懲基金結算</h2><div class="kpi"><div><b>罰款</b><br>$${t.fine}</div><div><b>獎勵</b><br>$${t.reward}</div><div><b>基金</b><br>$${t.balance}</div></div><hr>${state.records.map(r=>`<p>${r.type==='fine'?'罰款':'獎勵'}｜${r.store||'整區'}｜${r.reason}｜$${r.amount}｜${r.createdByName}</p>`).join('')}</div><div class="list">${state.records.map(r=>row(`${r.type==='fine'?'罰款':'獎勵'} $${r.amount}`,`${r.store||'整區'}｜${r.reason}`,r.id,'records')).join('')}</div>`),bindHistory();
if(state.tab==='admin') return shell(isAdmin()?adminHtml():`<div class="card"><h2>⚙️ 管理中心</h2><p>只有管理員可以使用。</p></div>`),bindAdmin();}
function isAdmin(){return state.user?.role==='admin'}
function row(title,sub,id,col){return `<div class="row"><div><b>${title}</b><div class="small muted">${sub||''}</div></div>${isAdmin()?`<button class="secondary" data-del="${id}" data-col="${col}">刪除</button>`:''}</div>`}
function bindDelete(){document.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{if(confirm('確定刪除？'))await deleteDoc(doc(db,b.dataset.col,b.dataset.del));});}
function bindFine(){document.querySelectorAll('[data-fine]').forEach(b=>b.onclick=async()=>addDoc(collection(db,'records'),{type:'fine',store:$('#store').value,reason:b.dataset.fine,amount:+b.dataset.amt,createdBy:state.user.employeeId,createdByName:state.user.name,createdAt:serverTimestamp()}));}
function bindReward(){document.querySelectorAll('[data-reward]').forEach(b=>b.onclick=async()=>addDoc(collection(db,'records'),{type:'reward',reason:b.dataset.reward,amount:+b.dataset.amt,createdBy:state.user.employeeId,createdByName:state.user.name,createdAt:serverTimestamp()}));}
function bindFund(){bindDelete();$('#addFund').onclick=async()=>{let a=+$('#amt').value;if(!a)return alert('請輸入金額');await addDoc(collection(db,'fundLedger'),{kind:$('#kind').value,amount:a,note:$('#note').value,createdBy:state.user.employeeId,createdByName:state.user.name,createdAt:serverTimestamp()});};}
function bindHistory(){bindDelete();$('#exportImg').onclick=()=>window.print(); const btn=$('#closeMonth'); if(btn)btn.onclick=closeMonth;}
async function closeMonth(){if(!confirm('確定本月結算？會把本月獎懲加進區基金，並清空本月獎懲紀錄。'))return;const t=totals();await addDoc(collection(db,'settlements'),{fine:t.fine,reward:t.reward,balanceAfter:t.balance,records:state.records,createdBy:state.user.employeeId,createdAt:serverTimestamp()});await updateDoc(doc(db,'meta','settings'),{fundBalance:t.balance});const batch=writeBatch(db);state.records.forEach(r=>batch.delete(doc(db,'records',r.id)));await batch.commit();alert('結算完成，已歸零本月獎懲。');}
function adminHtml(){return `<div class="card"><h2>⚙️ 管理中心</h2><div class="grid"><div class="field"><label>員編</label><input id="newId"></div><div class="field"><label>姓名</label><input id="newName"></div></div><div class="field"><label>權限</label><select id="newRole"><option value="staff">一般</option><option value="admin">管理員</option></select></div><button id="addUser">新增帳號｜預設密碼=員編</button></div><div class="list">${state.users.map(u=>`<div class="row"><div><b>${u.name}</b><div class="small muted">${u.employeeId}｜${u.role}</div></div>${u.employeeId==='5052'?'':'<button class="secondary" data-userdel="'+u.employeeId+'">刪除</button>'}</div>`).join('')}</div>`}
function bindAdmin(){if(!isAdmin())return;$('#addUser').onclick=async()=>{let id=$('#newId').value.trim(),name=$('#newName').value.trim(); if(!id||!name)return alert('請輸入員編與姓名'); await setDoc(doc(db,'users',id),{employeeId:id,name,password:id,role:$('#newRole').value,active:true,createdAt:serverTimestamp()});};document.querySelectorAll('[data-userdel]').forEach(b=>b.onclick=async()=>{if(confirm('刪除此帳號？'))await deleteDoc(doc(db,'users',b.dataset.userdel));});}
init();
